name: PR Test
 
on:
  pull_request:
    branches: [ main ] # master branch에 PR을 보낼 때 실행
 
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
#       - name: Build and Run Tests
#         run: test/
#       - name: Publish Test Report
#         uses: mikepenz/action-junit-report@v2
#         if: always() # always run even if the previous step fails
#         with:
#           report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: test-results/**/*.xml
